version: '3.3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${DB_USER:-airflow}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-airflow}
            - POSTGRES_DB=${DB_TYPE:-airflow}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"

    webserver:
        image: higbee/airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
            - AIRFLOW__CORE__EXECUTOR=${AIRFLOW_EXECUTOR:-LocalExecutor}
            - AIRFLOW__CORE__LOAD_EXAMPLES=${LOAD_EXAMPLES:-False}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        #volumes:
            #- pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        #networks:
         #   - postgres
        restart: unless-stopped
        
    influxdb:
        # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
        #build:
            # context: ./images/influxdb/
            #dockerfile: ./${TYPE}/Dockerfile
            #args:
            # INFLUXDB_TAG: ${INFLUXDB_TAG}access
        image: higbee/influxdb
        volumes:
            # Mount for influxdb data directory
            - ./influxdb/data:/var/lib/influxdb
            # Mount for influxdb configuration
            - ./influxdb/config/:/etc/influxdb/
        #command: ["influxd", "restore", "-metadir", "/var/lib/influxdb/meta", "-datadir", "/var/lib/influxdb/data", "-database", "cta", "/backups/cta_bak/"]
        #command: influxd restore -metadir /var/lib/influxdb/meta -datadir /var/lib/influxdb/data -database cta /var/lib/influxdb/backup
        ports:
            # The API for InfluxDB is served on port 8086
            - "8086:8086"
            - "8082:8082"
